### ISSUE TITLE
question: how to access param data in URL?

### ISSUE THREAD

**Issue by anantonton** [msavin/Parrot#6]
Hello @msavin. Thank you for creating this. I've been using Meteor since 1.1 and now in 1.8 iron:router (finally) gives up working and I stumbled upon Parrot. 

Usually using iron:router I do `Router.current().params.xxxx` all the time to access param value. Does Parrot have this kind of function?

Thank you!

**Comment by msavin** [comment]
Yes, you can do Parrot.get(param) and Parrot.set(param, value) :) it's
reactive too

**Comment by anantonton** [comment]
Thank you! And thank you too for making mongol and other cool tools!
